### ISSUE TITLE
Using without explicitly installing

### ISSUE THREAD

**Issue by der-flo** [asmeurer/prefsync#9]
The readme file suggests `python -m prefsync` to use the tool without explicitly installing it.

```
$ git clone https://github.com/asmeurer/prefsync.git
$ cd prefsync
$ python -m prefsync
/usr/bin/python: No module named prefsync.__main__; 'prefsync' is a package and cannot be directly executed
```

I don't know python so I can't handle this error. I want to avoid using `python setup.py install` because this requires root privileges, which makes my dotfile-scripts even harder.

**Comment by asmeurer** [comment]
Ah I must have written that before distutils forced me to make it into a package (it was originally just a script). I pushed a fix. 

By the way, I haven't tested this in awhile (not since a few OS X versions), so you'll have to let me know if it still works :)

**Comment by der-flo** [comment]
> Ah I must have written that before distutils forced me to make it into a package (it was originally just a script). I pushed a fix.

Thanks, works!
> By the way, I haven't tested this in awhile (not since a few OS X versions), so you'll have to let me know if it still works :)

Be sure to receive more issue requests in the next weeks if more problems arise ;-)
